import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Azmonk31Five</Link>
        </li>
        <li>
          <Link to="/azmonk31eleven">Azmonk31Eleven</Link>
        </li>
        <li>
          <Link to="/azmonk31nine">Azmonk31Nine</Link>
        </li>
        <li>
          <Link to="/azmonk31three">Azmonk31Three</Link>
        </li>
        <li>
          <Link to="/azmonk31two">Azmonk31Two</Link>
        </li>
        <li>
          <Link to="/azmonk31six">Azmonk31Six</Link>
        </li>
        <li>
          <Link to="/azmonk31seven">Azmonk31Seven</Link>
        </li>
        <li>
          <Link to="/azmonk31four">Azmonk31Four</Link>
        </li>
        <li>
          <Link to="/azmonk31eight">Azmonk31Eight</Link>
        </li>
        <li>
          <Link to="/azmonk31ten">Azmonk31Ten</Link>
        </li>
        <li>
          <Link to="/azmonk31one">Azmonk31One</Link>
        </li>
        <li>
          <Link to="/azmonk31">Azmonk31</Link>
        </li>
        <li>
          <Link to="/azmonk31twelve">Azmonk31Twelve</Link>
        </li>
        <li>
          <Link to="/presentationpreviewexpand">PresentationPreviewExpand</Link>
        </li>
        <li>
          <Link to="/frame2609435">Frame2609435</Link>
        </li>
        <li>
          <Link to="/frame2609436">Frame2609436</Link>
        </li>
        <li>
          <Link to="/frame2609437">Frame2609437</Link>
        </li>
        <li>
          <Link to="/frame2609438">Frame2609438</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
